/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/theme/Card.vue')['default']
    Counter: typeof import('./src/components/home/Counter.vue')['default']
    FlexMinified: typeof import('./src/components/FlexMinified.vue')['default']
    Footer: typeof import('./src/layouts/Footer.vue')['default']
    GridMinified: typeof import('./src/components/GridMinified.vue')['default']
    Header: typeof import('./src/layouts/Header.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    Info: typeof import('./src/components/tickets/zone/Info.vue')['default']
    Intro: typeof import('./src/components/home/Intro.vue')['default']
    LangMenu: typeof import('./src/components/LangMenu.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    LocationsFlex: typeof import('./src/components/LocationsFlex.vue')['default']
    LocationsMap: typeof import('./src/components/LocationsMap.vue')['default']
    Menu: typeof import('./src/layouts/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTable: typeof import('./src/components/schedules/table/ScheduleTable.vue')['default']
    Sections: typeof import('./src/components/about/Sections.vue')['default']
    Services: typeof import('./src/components/home/Services.vue')['default']
    SkeletonSchedules: typeof import('./src/components/skeletons/SkeletonSchedules.vue')['default']
    SkeletonSchedulesExact: typeof import('./src/components/skeletons/SkeletonSchedulesExact.vue')['default']
    SkeletonStops: typeof import('./src/components/skeletons/SkeletonStops.vue')['default']
    SkeletonTickets: typeof import('./src/components/skeletons/SkeletonTickets.vue')['default']
    Ticket: typeof import('./src/components/tickets/zone/Ticket.vue')['default']
    TicketLabel: typeof import('./src/components/tickets/zone/TicketLabel.vue')['default']
    Timeline: typeof import('./src/components/home/Timeline.vue')['default']
    Tracking: typeof import('./src/components/schedules/Tracking.vue')['default']
    Zone: typeof import('./src/components/tickets/Zone.vue')['default']
    ZonePerArea: typeof import('./src/components/tickets/ZonePerArea.vue')['default']
  }
}
